In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Conv1D, MaxPooling1D, Dropout, Activation
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [12]:
# Read in data

In [13]:
df = pd.read_csv("../data/recipe_phrases.csv", index_col=None,dtype={'phrase': np.str, 'is_ingredient': np.int})
df['phrase'] = df['phrase'].str.strip().str.lower().str.replace('?', '/')
df = df.fillna('')

In [22]:
X = df.phrase.values
y = df.is_ingredient.values

array(['sugar', 'knead to an elastic dough.',
       'bring mixture to the boil.', ..., 'dressing8  ounces  sour cream',
       'bake for 15-20 minutes at 400f.',
       'to the siftings or bran, add the water boiled and strained, then throw in the hops and sugar.'],
      dtype=object)

In [18]:
# Tokenize data

In [52]:
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)
data_X = pad_sequences(sequences, maxlen=300)

In [54]:
print(data_X)

[[  0   0   0 ... 631   2 813]
 [  0   0   0 ...  19   1  32]
 [  0   0   0 ...   8  72  59]
 ...
 [  0   0   0 ...  39  41 153]
 [  0   0   0 ... 134 109 807]
 [  0   0   0 ...  22   4  23]]


In [55]:
# RNN with LSTM

In [62]:
model = Sequential()
model.add(Embedding(10000, 128, input_length=300))
model.add(Dropout(0.2))
model.add(Conv1D(64, 5, activation='relu'))
model.add(MaxPooling1D(pool_size=4))
model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [63]:
# Train

In [65]:
model.fit(data_X, y, validation_split=0.75, epochs=3)

Train on 2321 samples, validate on 6964 samples
Epoch 1/3
2321/2321 [==============================] - 17s 7ms/step - loss: 0.0065 - acc: 0.9974 - val_loss: 0.0639 - val_acc: 0.9805
Epoch 2/3
2321/2321 [==============================] - 17s 7ms/step - loss: 0.0020 - acc: 0.9996 - val_loss: 0.0669 - val_acc: 0.9805
Epoch 3/3
2321/2321 [==============================] - 18s 8ms/step - loss: 8.8667e-04 - acc: 1.0000 - val_loss: 0.0701 - val_acc: 0.9806
